name: Deploy CMS (Railway)

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - "apps/cms/**"
      - "packages/ui/**"
      - "packages/config/**"
      - "package.json"
      - "pnpm-lock.yaml"
      - ".github/workflows/deploy-cms.yml"

jobs:
  quality-checks:
    name: Quality Checks (cms)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm --filter cms lint

      - name: Typecheck
        run: pnpm --filter cms typecheck

      - name: Format check
        run: pnpm --filter cms format

  deploy:
    name: Deploy to Railway
    needs: quality-checks
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_CMS_SERVICE_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Deploy service
        run: |
          railway login --service-token "$RAILWAY_TOKEN"
          railway up --service "$RAILWAY_SERVICE_ID" --ci
